### ISSUE TITLE
getCurrentMap() returns HTTP status was '404 Not Found'

### ISSUE THREAD

**Issue by kcs3** [waldronlab/HGNChelper#1]
Version: 0.5.2
Date: 2018-07-05

> library(HGNChelper)
> new.hgnc.table <- getCurrentHumanMap()
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'http://www.genenames.org/cgi-bin/hgnc_downloads?col=gd_hgnc_id&col=gd_app_sym&col=gd_prev_sym&col=gd_aliases&status=Approved&status=Entry+Withdrawn&status_opt=2&where=&order_by=gd_hgnc_id&format=text&limit=&hgnc_dbtag=on&submit=submit': HTTP status was '404 Not Found'

**Comment by lwaldron** [comment]
Thanks @kcs3. The HGNC seems to have changed their downloads page. Working on finding the right data again.

**Comment by kcs3** [comment]
Thanks, good luck!

**Comment by lwaldron** [comment]
I think this is resolved in 0beff7d (version 0.7.0). The HGNC map is bigger now, I think because the file I use now includes  symbols for non-coding RNA, pseudogenes, and some other things (see the "Locus type" help at genenames.org). @kcs3 I would really appreciate it if you could give it a try here and let me know if it passes your sanity check before I upload to CRAN.

**Comment by lwaldron** [comment]
Resolved with 0beff7d15c748f44f276636e48033ad8f750ea2d, release 0.7.1 was submitted to CRAN this morning.

**Comment by boutrys** [comment]
Hello, 

Thanks for the great package and all the work, 

small details : I think the package should be updated because the getCurrentHumanMap() does not work anymore 

Fetching human gene symbols from ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt
trying URL 'ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt'
Error in download.file(url, destfile = "hgnc_complete_set.txt") : 
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt'
In addition: Warning message:
In download.file(url, destfile = "hgnc_complete_set.txt") :
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt': FTP status was '550 Requested action not taken; file unavailable'
  
  By doing that 
  url <- "storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt"
destfile <- "hgnc_complete_set.txt"
new_hgnc_table <- download.file(url, destfile)

then I can use 
new_hgnc_table <- getCurrentHumanMap()
and it worked 
Using the already downloaded hgnc_complete_set.txt file.
Warning messages:
1: In type.convert.default(X[[i]], ...) :
  'as.is' should be specified by the caller; using TRUE
2: In type.convert.default(X[[i]], ...) :
  'as.is' should be specified by the caller; using TRUE
3: In type.convert.default(X[[i]], ...) :
  'as.is' should be specified by the caller; using TRUE
4: In type.convert.default(X[[i]], ...) :
  'as.is' should be specified by the caller; using TRUE
5: In type.convert.default(X[[i]], ...) :
  'as.is' should be specified by the caller; using TRUE
6: In type.convert.default(X[[i]], ...) :
  'as.is' should be specified by the caller; using TRUE
  
  
  packageVersion("HGNChelper")
[1] ‘0.8.14’

Best wishes

Simon
